typescript/.changeset/pink-coats-battle.md, typescript/packages/core/src/tools.ts
Update the Tool and DeferredTool interfaces to allow methods to return any result.
=> feat: allow tools to return any result

typescript/packages/core/src/utils.ts
Previously, the parameters for send_eth were not correctly parsed, due to it being a self implemented method. It was failing the instanceOf check, so we moved to schema._def?.typeName check instead.
Bug fix
Locally
- [] I have tested this change locally with key pair wallets
=> fix: parameters for sending eth

typescript/packages/plugins/orca/package.json, typescript/packages/plugins/orca/src/index.ts, typescript/packages/plugins/orca/src/orca.plugin.ts, typescript/packages/plugins/orca/src/orca.service.ts, typescript/packages/plugins/orca/src/parameters.ts, typescript/packages/plugins/orca/tsconfig.json, typescript/packages/plugins/orca/tsup.config.ts, typescript/pnpm-lock.yaml
Allows the  agent to create single sided pools on Orca.
New plugin
I used the branch `joyce-branch` and used the conversational agent in `GOAT/typescript/examples/vercel-ai/solana` to test pool creation. Here's a sample conversation with the agent and Devnet transaction:
https://solscan.io/tx/5BJ5UkomwKeUGSCLscJU4rWEZy3n75KeSyeBPg6JiQnQP3HG2FhdueXjGdtMGxuCJFukgBM9kHKMLSP5emJb15dK?cluster=devnet
@calintje
=> Add single sided pool creation on Orca

typescript/packages/plugins/orca/src/orca.service.ts
Previously, the code was set to work with the Whirlpool Program on Devnet by having the WhirlpoolsConfig address set to the one on Devnet. This fix updates the WhirlpoolsConfig address to the one on Mainnet. For more information about WhirlpoolsConfig:
👉 [doc on Account Architecture](https://orca-so.github.io/whirlpools/Architecture%20Overview/Account%20Architecture#whirlpoolsconfig)
👉 [doc on Whirlpool Parameters](https://orca-so.github.io/whirlpools/Architecture%20Overview/Whirlpool%20Parameters)
Fix
My changes require no change to the project documentation.
@calintje
=> Update WhirlpoolsConfig address

typescript/packages/wallets/evm/src/types/EVMTransaction.ts, typescript/packages/wallets/viem/src/ViemEVMWalletClient.ts
Adds a data parameter to EVM transaction. Some tools need it as they require for some encoded data to eb sent alognside the tx
A wallet plug in change
None, automated tests are fine as this is an optional param
- [NO] I have tested this change locally with hosted wallets (e.g. Crossmint Smart Wallets, etc.) - filing a task for this
alfongj
=> [Wallet] EVMWallets can take an arbitrary 'data' param now

typescript/packages/plugins/orca/src/orca.service.ts, typescript/packages/wallets/solana/src/SolanaKeypairWalletClient.ts, typescript/pnpm-lock.yaml
This PR adds the following 3 things:
- Single Sided pool creation can now be done on Devnet
- Changed the wrapping strategy for SOL to reduce transaction size in case the agent does not have WSOL account
- Update send transaction logic. I took the liberty to update the function to optimize it for transaction landing, which is especially important in DeFi operations, including:
- Include computeBugetSetUnitLimit instruction
- Replace the deprecated 'confirmTransaction' API method: https://solana.com/docs/rpc/deprecated/confirmtransaction
- Client-side retry mechanism. https://www.helius.dev/blog/how-to-land-transactions-on-solana
Update/improvement
Used vercel-ai Solana example.
prompt: single sided pool on orca: deposit …
=> Update send transaction and orca tool

typescript/packages/plugins/erc20/src/erc20.service.ts, typescript/packages/plugins/erc20/src/parameters.ts, typescript/packages/wallets/solana/src/SolanaKeypairWalletClient.ts
While using the ERC20 plugin for a portfolio manager, I noticed that the following prompt does not work to revoke approvals for ERC20 tokens.
>Revoke approval for PEPE tokens to 0x9d85494061dFdf8ad40B3aB3A73E897CA5F4f27B
I think adding support for prompts like this this will be useful for many ERC20 plugin use-cases such as trading agents, portfolio managers, tipping bots etc. Adding this tool will allow users to easily revoke approvals using generic prompts such as the one I tried above.
This PR adds a new tool to the ERC20 plugin: `revokeApproval`
- Add new parameter `RevokeApprovalParameters` which contains only spender and token address
- Use parameters in the `revokeApproval` action to set approval amount to 0 for the given spender and token address
After adding the new tool, I used …
=> Add revoke approval tool for ERC20 plugin

typescript/biome.json, typescript/examples/vercel-ai/headless-checkout/index.ts, typescript/examples/vercel-ai/modespray/index.ts, typescript/packages/plugins/coingecko/src/request.ts, typescript/packages/plugins/crossmint-headless-checkout/src/crossmint-headless-checkout.plugin.ts, typescript/packages/plugins/dexscreener/src/dexscreener.plugin.ts, typescript/packages/plugins/ironclad/src/ironclad.plugin.ts, typescript/packages/plugins/jupiter/src/parameters.ts, typescript/packages/plugins/kim/src/kim.service.ts, typescript/packages/plugins/mode-governance/src/index.ts, typescript/packages/plugins/orca/src/tools/openSingleSidedPosition.ts, typescript/packages/plugins/renzo/src/renzo.service.ts, typescript/packages/plugins/zerodev-global-address/src/zerodev-global-address.service.ts, typescript/packages/wallets/chromia/src/ChromiaWalletClient.ts
We can clean up unused imports by adding a new linter rule: `noUnusedImports`. There were 13 files with unused imports.
- Adds a new linter rule: `noUnusedImports`
- Fixes 13 files using `pnpm lint:fix`
I don't believe any testing is required. There should be no chance of regression. The Biome rule has a safe fix as described [here](https://biomejs.dev/linter/rules/no-unused-imports/).
toozol1
=> Remove unused imports with new linter rule

goat.code-workspace, typescript/.changeset/six-pillows-decide.md, typescript/packages/core/src/types/Chain.ts, typescript/packages/plugins/zilliqa/README.md, typescript/packages/plugins/zilliqa/package.json, typescript/packages/plugins/zilliqa/src/index.ts, typescript/packages/plugins/zilliqa/src/parameters.ts, typescript/packages/plugins/zilliqa/src/plugin.ts, typescript/packages/plugins/zilliqa/src/zilliqa.service.ts, typescript/packages/plugins/zilliqa/tsconfig.json, typescript/packages/plugins/zilliqa/tsup.config.ts, typescript/packages/plugins/zilliqa/turbo.json, typescript/packages/wallets/viem/package.json, typescript/packages/wallets/viem/src/ViemEVMWalletClient.ts, typescript/packages/wallets/zilliqa/README.md, typescript/packages/wallets/zilliqa/package.json, typescript/packages/wallets/zilliqa/src/ZilliqaWalletClient.ts, typescript/packages/wallets/zilliqa/src/index.ts, typescript/packages/wallets/zilliqa/tsconfig.json, typescript/packages/wallets/zilliqa/tsup.config.ts, typescript/packages/wallets/zilliqa/turbo.json, typescript/pnpm-lock.yaml
This PR adds a wallet and plugin for the Zilliqa blockchain which can cope with both Zilliqa and EVM native addresses; once the approach is validated, we can start to add native (ZRC-2) token transactions and support for DEXes , etc.
- Instantiate the wallet
- Try invoking the actions.
There's a fork of Eliza which (with suitable `pnpm link`'ing) can do this at  https://github.com/rrw-zilliqa/eliza/tree/rrw , but I can't submit that upstream until this is merged.
(below is with Eliza via the code at  https://github.com/rrw-zilliqa/eliza/tree/rrw )
| get Zilliqa address | what's your zilliqa address? |  ![image](https://github.com/user-attachments/assets/3555edf0-9b7a-4bff-8c1d-ca8dc154bbd9) …
=> (feat) Add a chain type, wallet and plugin for the Zilliqa blockchain

typescript/examples/vercel-ai/mode/index.ts
The current implementation throws an error when users provide a private key without the '0x' prefix, even if the key itself is valid. This creates unnecessary friction for users.
- Adds automatic prefixing of '0x' to private keys when missing
- Maintains existing validation for correct key length (66 characters including '0x')
- Provides seamless handling of private keys whether they include the prefix or not
wispyiwnl
=> Add automatic 0x prefix to private key handling

typescript/packages/wallets/zilliqa/src/ZilliqaWalletClient.ts
fixes #241 
It removes the static initialization of `chainId`, which causes ts to no longer generate invalid Javascript when exporting CJS modules.
Attempt to import the npm-released version of `wallet-zilliqa`.
I'm going to n/a this until requested to do so, because there's quite a lot of of it and this is quite a small PR - do yell if you want the full shebang.
no change required to project docs.
- [X ] I have tested this change locally with key pair wallets
- [ n/a] I have tested this change …
=> (fix) CJS distribution for wallet-zilliqa

python/src/goat-sdk/goat/classes/plugin_base.py, python/src/goat-sdk/pyproject.toml
Fixes #245 
As noted by #245 , our current approach to async tool calling is not robust.
This PR addresses the problem by considering these cases whenever an async tool is being called:
1. If there's an existing event loop and it's not running: use it directly with run_until_complete.
2. If there's an existing event loop and it's running: create a new thread with its own event loop to avoid deadlock.
3. If there's no event loop: create a new one and use it, then set it as the current event loop to be reused.
=> Python fix: deal with several async settings upon calling async tools

typescript/.changeset/soft-ducks-develop.md, typescript/examples/eleven-labs/conversational-agent/src/app/utils/index.ts, typescript/packages/wallets/crossmint/src/wallets/CustodialSolanaWalletClient.ts, typescript/packages/wallets/lit-protocol/src/solana.ts, typescript/packages/wallets/solana/src/SolanaKeypairWalletClient.ts, typescript/packages/wallets/solana/src/SolanaWalletClient.ts
=> chore: Add raw tx interface

python/src/goat-sdk/goat/decorators/tool.py, python/src/goat-sdk/poetry.lock, python/src/goat-sdk/pyproject.toml, python/src/wallets/evm/goat_wallets/evm/types.py, python/src/wallets/evm/poetry.lock, python/src/wallets/evm/pyproject.toml
While integrating GOAT into an AI Agent framework, our CI (that runs on Python 3.10 up to 3.13, which is the same version range that you are supposed to support according to your `pyproject.toml`), the [build failed](https://github.com/Libertai/libertai-agents/actions/runs/12911959806/job/36005623413#step:6:44) due to a Python type only available in Python 3.11 and onwards that you're importing.
This PR fixes it by adding `typing_extensions` to support it, therefore making GOAT importable in Python 3.10 projects.
It would probably be best to add a GitHub Action with a matrix to check if the project correctly builds in all the Python versions you support to automate this check and avoid future issues.
Else you can manually create a Python 3.10 project and import GOAT inside and notice the …
=> fix(python): Unsupported type in Python 3.10

typescript/.changeset/soft-fans-play.md, typescript/packages/wallets/evm/src/sendETH.plugin.ts
=> Remove viem dependency on sendETH

typescript/.changeset/breezy-pants-know.md, typescript/packages/plugins/plunderswap/src/types.ts
No issue/ticket.
Removes `toAddress` parameter from the `plunderswap_swap` tool: it is misleading to offer it because the tool ignores it.
(For safety, the tool's actual implementation always deposits currency back into the user's wallet. We don't want the user accidentally giving somebody else the tokens because their address was in the conversation history.)
Use the instructions from the description of https://github.com/elizaOS/eliza/pull/3267 to get going with ElizaOS. Locally, adjust `packages/plugin-zilliqa/package.json` to have ElizaOS' `@goat-sdk/plugin-plunderswap` dependency link to wherever this branch's `typescript/packages/plugins/plunderswap` is.
Try doing any swap with `plunderswap_swap` and see that the tokens are deposited back into your wallet.
Links to transactions:
1. …
=> Fix PlunderSwap plugin API: remove ignored tool parameter.

typescript/packages/plugins/debridge/package.json
@goat-sdk/plugin-debridge not being published on npm
=> Update deBridge package.json

python/examples/by-wallet/crossmint/solana_smart_wallet_creation_examples.py, python/examples/by-wallet/crossmint/solana_smart_wallet_delegated_signer_example.py, python/examples/by-wallet/crossmint/solana_smart_wallet_fireblocks_signer_example.py, python/examples/by-wallet/crossmint/solana_smart_wallet_keypair_admin_signer_example.py, python/examples/by-wallet/crossmint/solana_smart_wallet_transfer_example.py, python/src/wallets/crossmint/goat_wallets/crossmint/__init__.py, python/src/wallets/crossmint/goat_wallets/crossmint/api_client.py, python/src/wallets/crossmint/goat_wallets/crossmint/parameters.py, python/src/wallets/crossmint/goat_wallets/crossmint/solana_smart_wallet.py, python/src/wallets/crossmint/goat_wallets/crossmint/solana_smart_wallet_factory.py, python/src/wallets/crossmint/goat_wallets/crossmint/types.py
This PR:
- Simplifies the interface for SSW
- Fixes the factory
- Fixes creation with linked users
- Fixes differences between wallet locators and user locators
- Fixes getting the wallet balance
- Implements Crossmint-style wallet balance
- Implements idempotency on wallet creation
- Adds examples for SOL transfer
- Adds examples for wallet creation
Many test cases have been tested:
- Sending SPL
- Delegated signers (+send transaction)
- Creating wallets with _many_ different configurations, including different signers and linked users
- Tested idempotency
- Retrieving balance
Tou can go a run these new examples yourself
=> Crossmint(SSW): Fixes

python/examples/by-wallet/crossmint/solana_smart_wallet_swap_example.py, python/src/plugins/jupiter/goat_plugins/jupiter/service.py, python/src/plugins/jupiter/pyproject.toml, python/src/wallets/crossmint/goat_wallets/crossmint/solana_smart_wallet.py, python/src/wallets/crossmint/tests/conftest.py, python/src/wallets/crossmint/tests/test_solana_smart_wallet.py
We're passing a base64 tx where the send_raw_transaction expects base58. This fixes that and adds a mechanism to prevent these situations in the future by, if the b58 decoding fails, it tries to decode it b64.
=> Solana Smart Wallets: fix b64 tx

python/src/wallets/crossmint/goat_wallets/crossmint/solana_smart_wallet.py, python/src/wallets/crossmint/pyproject.toml
Smart Wallet with Solana Keypair admin signer
In some transactions, we were encountering issues with:
Missing signature: where the transaction would fail because the signer was not properly attached
Too many signatures: where additional_signers were being appended multiple times, causing redundant signatures.
This PR improves the transaction signing flow by:
- Updating `send_transaction()` to fallback to `self._admin_signer` if no signer is provided in the transaction payload.
- Cleaning up `send_raw_transaction()` to prevent duplication in the signers list by ensuring `additional_signers` are only appended once.
These changes ensure the correct signer is always present and that transactions include the required, but only necessary, signatures — resolving both the missing and excessive …
=> Fixing Smart Wallet with Solana Keypair admin signer issues

typescript/packages/plugins/velodrome/src/velodrome.service.ts
This PR fixes the previous issues that prevented adding liquidity to Velodrome. With these changes, liquidity can now be successfully added to any pool on Velodrome, except for pairs involving ETH.
To test the plugin, run it from: `typescript/examples/by-use-case/evm-defi-agent `
| addLiquidity | Add liquidity to the volatile USDC MODE pool using velodrome with 1 USDC and 238 MODE. Send LP tokens to my wallet. | ![addLiquidity0](https://github.com/user-attachments/assets/0cb10bf4-c690-487f-9e03-96316552311f)![addLiquidity1](https://github.com/user-attachments/assets/430bddc9-c7a3-47e1-b3b7-4c41eb1a65d0) | [Transaction link](https://explorer.mode.network/tx/0xa4dc9ec0b27103c0cb2f3c3f176849c6 …
=> fix: correct addLiquidity errors on Velodrome

typescript/packages/plugins/orderly-network/src/orderly-network.service.ts
- The createOrderOrderly function has been updated to avoid the error when opening market orders in Futures mode. Now, for MARKET orders, order_price is set to undefined, and for BUY orders, order_amount is discarded (set to undefined) so that only the base unit value is used.
- The allowed symbol lookup logic was adjusted by using parameters.token.toUpperCase() in the comparison, ensuring that the search is case-insensitive.
1. Run an example that attempts to create a market BUY order in Futures mode.
2. Verify that the order is processed without the error "In Futures mode, BUY orders do not support order_amount".
3. Confirm that the allowed symbol lookup works correctly by converting the token to uppercase. …
=> fix(orderly-network): streamline order creation logic and improve parameter handling

typescript/packages/plugins/polymarket/src/api.ts, typescript/packages/plugins/polymarket/src/utils.ts
The `get_polymarket_events` tool (and underlying API function) was failing due to two issues related to the `outcomePrices` field returned by the Polymarket API:
1.  **Zod Validation Error:** The internal `Event` schema in `api.ts` defined `outcomePrices` as a required `string`. However, the Polymarket API sometimes omits this field, causing a Zod validation error (`"Required"`).
2.  **JSON Parse Error:** The `transformMarketOutcomes` helper function in `utils.ts` unconditionally called `JSON.parse()` on `outcomePrices`. When the field was missing (and thus `undefined` after the schema change), this resulted in a `JSON Parse error: Unexpected identifier "undefined"`.
This PR addresses both issues:
1.  **Schema Update (`api.ts`):** Marks `outcomePrices` as `.optional()` in the `Event` Zod …
=> Fix(plugin-polymarket): Handle optional outcomePrices in get_events response

README.md, package-lock.json, typescript/.changeset/twenty-penguins-invent.md, typescript/packages/plugins/lulo/README.md, typescript/packages/plugins/lulo/src/lulo.service.ts, typescript/packages/plugins/lulo/src/parameters.ts
Adds withdraw USDC functionality to the Lulo plugin
The Lulo plugin currently only supported deposits. This PR adds the ability to withdraw USDC from Lulo as well, which completes the basic DeFi functionality for the plugin.
1. Adds a new `withdrawUSDC` method to the Lulo service
2. Creates a `WithdrawTokenParameters` class with amount and token parameters
3. Registers the withdrawal function as a tool with the GOAT framework
1. Install the examples/by-use-case/solana-usdc-yield-deposit example
2. Link the local version of the Lulo plugin: `"@goat-sdk/plugin-lulo": "file:../../../packages/plugins/lulo"`
3. Run the example and test both deposit and withdrawal functionality
| …
=> feat: Lulo USDC withdraw
