goat-sdk/goat

docs/wallets.mdx

Adds Dynamic.xyz example
Docs
None
None
N/A

feat: add Dynamic example for Eth

---

.github/actions/pnpm-install/action.yml
.github/workflows/ci.yml
goat.code-workspace

fix ci working dir
CI passes for this branch

ci: fix working dir

---

.github/workflows/ci-cd-main.yml

hopefully this fixes changesets red in main

cd: change yml permission

---

typescript/examples/eleven-labs/conversational-agent/package.json
typescript/examples/langchain/viem/package.json
typescript/examples/vercel-ai/abstract/package.json
typescript/examples/vercel-ai/coingecko/package.json
typescript/examples/vercel-ai/crossmint-smart-wallets/package.json
typescript/examples/vercel-ai/crossmint-solana-custodial-wallets/package.json
typescript/examples/vercel-ai/polymarket/package.json
typescript/examples/vercel-ai/solana/package.json
typescript/examples/vercel-ai/viem/package.json
typescript/packages/adapters/eleven-labs/package.json
typescript/packages/adapters/eliza/package.json
typescript/packages/adapters/langchain/package.json
typescript/packages/adapters/vercel-ai/package.json
typescript/packages/core/package.json
typescript/packages/plugins/coingecko/package.json
typescript/packages/plugins/erc20/package.json
typescript/packages/plugins/polymarket/package.json
typescript/packages/plugins/solana-nfts/package.json
typescript/packages/wallets/crossmint/package.json
typescript/packages/wallets/solana/package.json
typescript/packages/wallets/viem/package.json
typescript/pnpm-lock.yaml
typescript/pnpm-workspace.yaml

start using catalog to keep versions in sync across plugins/examples

chore: use pnpm catalog

---

typescript/.changeset/smart-dogs-burn.md
typescript/packages/wallets/crossmint/src/custodial.ts

Missing wallet type in custodial wallet locator

fix: custodial locator

---

typescript/packages/plugins/spl-token/package.json
typescript/packages/plugins/spl-token/src/index.ts
typescript/packages/plugins/spl-token/src/methods/balance.ts
typescript/packages/plugins/spl-token/src/methods/transfer.ts
typescript/packages/plugins/spl-token/src/parameters.ts
typescript/packages/plugins/spl-token/src/plugin.ts
typescript/packages/plugins/spl-token/src/tokens.ts
typescript/packages/plugins/spl-token/src/utils/doesAccountExist.ts
typescript/packages/plugins/spl-token/src/utils/getTokenByMintAddress.ts
typescript/packages/plugins/spl-token/src/utils/getTokenMintAddressBySymbol.ts
typescript/packages/plugins/spl-token/src/utils/getTokensForNetwork.ts
typescript/packages/plugins/spl-token/src/utils/getTools.ts
typescript/packages/plugins/spl-token/tsconfig.json
typescript/packages/plugins/spl-token/tsup.config.ts
typescript/pnpm-lock.yaml

spl token plugin, only added usdc for now

plugin: spl token

---

.github/workflows/ci-pr.yml
typescript/biome.json
typescript/examples/eleven-labs/dynamic/src/app/components/conversation.tsx
typescript/examples/eleven-labs/dynamic/src/app/providers.tsx
typescript/packages/plugins/uniswap/package.json

trying to get prs from forked repos to correctly require approval to run

ci: change on trigger

---

typescript/packages/plugins/tensor/package.json
typescript/packages/plugins/tensor/src/index.ts
typescript/packages/plugins/tensor/src/methods/getBuyListingTransaction.ts
typescript/packages/plugins/tensor/src/methods/getNftInfo.ts
typescript/packages/plugins/tensor/src/parameters.ts
typescript/packages/plugins/tensor/src/plugin.ts
typescript/packages/plugins/tensor/src/tools.ts
typescript/packages/plugins/tensor/src/utils/decompileVersionedTransactionToInstructions.ts
typescript/packages/plugins/tensor/src/utils/deserializeTxResponseToInstructions.ts
typescript/packages/plugins/tensor/tsconfig.json
typescript/packages/plugins/tensor/tsup.config.ts
typescript/pnpm-lock.yaml

plugin: tensor

---

.github/workflows/ci-cd-main.yml
.github/workflows/ci-pr.yml

ci: add remote caching

---

typescript/examples/README.md

Fixes broken link in Example Readme

broken link fix

---

typescript/examples/vercel-ai/crossmint-solana-custodial-wallets/README.md

Command fix with the correct file name 
It updates command to `npx ts-node create-custodial-wallet.ts` from `npx ts-node create-smart-wallet.ts` 
Corrects the filename

Readme command fix

---

typescript/.changeset/tame-tomatoes-doubt.md
typescript/examples/vercel-ai/chromia/index.ts
typescript/packages/core/src/core-plugins/send-chr.ts
typescript/packages/wallets/chromia/src/index.ts
typescript/packages/wallets/crossmint/src/api.ts

- Add Transaction Hash for Chromia Mainnet Explorer
- Add wallet check validation to prevent sending to wrong address

Chr wallet check

---

typescript/packages/adapters/eleven-labs/src/index.ts
typescript/packages/adapters/eliza/src/index.ts
typescript/packages/adapters/langchain/src/index.ts
typescript/packages/adapters/vercel-ai/src/index.ts
typescript/packages/core/src/utils/addParametersToDescription.ts
typescript/packages/core/src/utils/index.ts

V2: fix adapters

---

typescript/biome.json
typescript/package.json
typescript/packages/core/package.json
typescript/packages/core/src/classes/PluginBase.ts
typescript/packages/core/src/decorators/Tool.ts
typescript/packages/core/src/symbol-polyfill.ts
typescript/packages/core/src/types/ClassMethodDecorator.ts
typescript/packages/core/src/utils/createToolParameters.ts
typescript/packages/core/src/utils/getTools.ts
typescript/packages/core/src/utils/index.ts
typescript/packages/core/tsconfig.json
typescript/packages/plugins/coingecko/src/coingecko.service.ts
typescript/packages/plugins/coingecko/src/parameters.ts
typescript/pnpm-lock.yaml
typescript/tsconfig.base.json
typescript/tsup.config.base.ts

V2: type safe decorator

---

goat.code-workspace
typescript/.changeset/short-trees-heal.md
typescript/packages/plugins/meteora/package.json
typescript/packages/plugins/meteora/src/index.ts
typescript/packages/plugins/meteora/src/meteora.plugin.ts
typescript/packages/plugins/meteora/src/meteora.service.ts
typescript/packages/plugins/meteora/src/parameters.ts
typescript/packages/plugins/meteora/tsconfig.json
typescript/packages/plugins/meteora/tsup.config.ts
typescript/packages/wallets/solana/src/SolanaKeypairWalletClient.ts
typescript/packages/wallets/solana/src/SolanaWalletClient.ts
typescript/packages/wallets/solana/src/types/SolanaTransaction.ts
typescript/pnpm-lock.yaml

feat: add accountsToSign parameter to txs + Meteora example

---

typescript/.changeset/grumpy-donkeys-prove.md
typescript/examples/vercel-ai/solana/index.ts
typescript/packages/wallets/solana/src/SolanaKeypairWalletClient.ts

fix: wait for tx confirmation on solana keypair send tx

---

typescript/packages/wallets/lit-protocol/src/solana.ts

Addressing error reported by [Discord user](https://discord.com/channels/1311079615732777010/1319359349612744705/1319359349612744705)

Fix viem import for formatUtils

---

typescript/examples/vercel-ai/polymarket/README.md
typescript/examples/vercel-ai/polymarket/index.ts
typescript/examples/vercel-ai/polymarket/package.json
typescript/packages/plugins/polymarket/src/api.ts
typescript/packages/plugins/polymarket/src/parameters.ts
typescript/packages/plugins/polymarket/src/tools.ts
typescript/packages/plugins/polymarket/src/utils.ts
typescript/pnpm-lock.yaml

It makes using polymarket easier
* Sets better defaults for the query events API
* Filters out the responses to remove irrelevant data - which increases the ability for the LLM to figure out how to chain these
* Makes the example an iterative CLI instead of a one-shot command
* Improves the example README with some missing steps
- As user, go to typescript/examples/vercel-ai/polymarket
  - Follow the README.md 
  - verify it has all the steps needed
  - ask the agent to fetch 5 recent bets related to trump, and to place a bet on one
- [N/A] I have tested this change locally with hosted wallets (e.g. Crossmint Smart Wallets, etc.)
alfongj

[Plug-in][Polymarket] Made the plug in more user-friendly

---

typescript/packages/wallets/viem/src/ViemEVMWalletClient.ts

N/A
This PR addresses an issue where the `simulateContract` function in the `ViemEVMWalletClient` was not passing the `value` parameter, leading to incorrect transaction simulations for contracts requiring a specific value.
- Adds the `value` parameter to the `simulateContract` function call in the `ViemEVMWalletClient.ts` file.
- Ensures proper handling of transactions with a specific `value`.
Bug fix.
1. Modify the `simulateContract` function call in the `ViemEVMWalletClient` file to include the `value` parameter.
2. Build the packages after making the change.
3. Test the updated function using a contract requiring a specific `value` to ensure the simulation works as expected.
- Before
- After
@AKAwolfcito

fix: add value to simulate contract

---

typescript/packages/plugins/modespray/README.md

[Plugin] ModeSpray
Improve Mode Spray Plugin Documentation.
- Fix typo in readme header
- Improve plugin description
@koha.gg

docs: improve Modespray plugin documentation

---

typescript/packages/wallets/evm/README.md

- Changed installation instructions to use @goat-sdk/wallet-viem instead of @goat-sdk/wallet-solana.
- Updated usage examples to reflect the new wallet client setup using viem.
- Removed Solana-specific code and dependencies, replacing them with viem-compatible imports and functionality.
- Added dotenv configuration for environment variables.
Fixes #136 
Update the README for EVM wallets 
N/A

Update README for wallet-viem integration and Solana removal

---

python/src/plugins/coingecko/poetry.lock
python/src/plugins/coingecko/pyproject.toml

Coingecko v0.1.1: depend on goat-sdk 0.1.1

---

typescript/examples/vercel-ai/mode/README.md

tell people to run form the directory

---

typescript/packages/wallets/evm/README.md

Update evm wallets readme

---

typescript/.changeset/polite-ligers-rhyme.md
typescript/packages/core/src/classes/WalletClientBase.ts
typescript/packages/plugins/crossmint-headless-checkout/src/crossmint-headless-checkout.plugin.ts
typescript/packages/plugins/crossmint-headless-checkout/src/parameters.ts
typescript/packages/plugins/crossmint-headless-checkout/turbo.json
typescript/packages/plugins/dexscreener/turbo.json
typescript/packages/plugins/worldstore/package.json
typescript/packages/plugins/worldstore/src/index.ts
typescript/packages/plugins/worldstore/src/parameters.ts
typescript/packages/plugins/worldstore/src/worldstore.plugin.ts
typescript/packages/plugins/worldstore/src/worldstore.service.ts
typescript/packages/plugins/worldstore/tsconfig.json
typescript/packages/plugins/worldstore/tsup.config.ts
typescript/packages/plugins/worldstore/turbo.json
typescript/pnpm-lock.yaml

plugin: worldstore

---

typescript/.changeset/stupid-guests-reply.md

pr#242
I failed to add a changeset to my previous PR, so we didn't release wallet-zilliqa, and I thus can't depend on it elsewhere. This PR hopefully fixes that issue.

(feat) Add changeset for the wallet-zilliqa package so as to pick up compile fix.

---

typescript/.changeset/tidy-mirrors-exist.md
typescript/packages/plugins/0x/src/0x.service.ts
typescript/packages/plugins/0x/src/parameters.ts
typescript/pnpm-lock.yaml

fix: 0x small fix

---

typescript/.changeset/loud-pumas-glow.md
typescript/packages/plugins/crossmint-headless-checkout/src/crossmint-headless-checkout.plugin.ts

headless: insufficient funds check

headless: insufficient funds check

---

typescript/README.md

When following setup instructions in the README, there are a few cases where invalid (non-existant) package names are being used.  
This updates the README to use the correct package names.

Fix incorrect package names in installation instructions

---

biome.json
typescript/.changeset/strong-owls-hug.md
typescript/packages/plugins/crossmint-headless-checkout/package.json
typescript/packages/plugins/crossmint-headless-checkout/src/crossmint-headless-checkout.plugin.ts
typescript/packages/plugins/crossmint-headless-checkout/src/parameters.ts
typescript/pnpm-lock.yaml

headless: update plugin

---

typescript/.changeset/smooth-news-compare.md
typescript/packages/plugins/crossmint-headless-checkout/package.json
typescript/packages/plugins/crossmint-headless-checkout/src/crossmint-headless-checkout.plugin.ts
typescript/pnpm-lock.yaml
typescript/pnpm-workspace.yaml

headless: pay w sol

---

typescript/examples/vercel-ai/enso/README.md
typescript/examples/vercel-ai/enso/index.ts

Update Enso example

---

typescript/packages/wallets/crossmint/src/index.ts

- expose the `solanaSmartWalletFactory` method

SSW: Expose in TS pckg

---

typescript/.changeset/ten-plants-retire.md

added missing changeset 
PR https://github.com/goat-sdk/goat/pull/370

add missing changeset (SSW: Expose in TS pckg [#370])

---

typescript/.changeset/ten-plants-retire.md
typescript/examples/by-use-case/evm-mint-nft/CHANGELOG.md
typescript/examples/by-use-case/evm-mint-nft/package.json
typescript/examples/by-use-case/solana-mint-nft/CHANGELOG.md
typescript/examples/by-use-case/solana-mint-nft/package.json
typescript/examples/by-wallet/crossmint-smart-wallets/CHANGELOG.md
typescript/examples/by-wallet/crossmint-smart-wallets/package.json
typescript/examples/by-wallet/crossmint-solana-custodial-wallets/CHANGELOG.md
typescript/examples/by-wallet/crossmint-solana-custodial-wallets/package.json
typescript/packages/wallets/crossmint/CHANGELOG.md
typescript/packages/wallets/crossmint/package.json

Revert "Release packages"

---

README.md

This commit adds the deBridge plugin link for the Python implementation to the goat-sdk docs.
The deBridge plugin for Python was merged but the main goat-sdk readme has not been updated to reflect this addition. Here is the [PR](https://github.com/goat-sdk/goat/pull/364) that merged the Python implementation.
This PR updates the readme of goat-sdk to add a link to the Python implementation of the deBridge plugin to make it easily discoverable.
This is a documentation change to the goat-sdk …

Update README.md - Add deBridge plugin link [Python]

---

.github/actions/poetry-install/action.yml
.github/workflows/ci-cd-main.yml
.github/workflows/ci-cd-python.yml
python/PUBLISHING.md
python/pyproject.toml
python/scripts/version_bump.py
python/src/adapters/langchain/pyproject.toml
python/src/goat-sdk/pyproject.toml
python/src/plugins/1inch/pyproject.toml
python/src/plugins/allora/pyproject.toml
python/src/plugins/coingecko/pyproject.toml
python/src/plugins/dexscreener/pyproject.toml
python/src/plugins/erc20/pyproject.toml
python/src/plugins/farcaster/pyproject.toml
python/src/plugins/jsonrpc/pyproject.toml
python/src/plugins/jupiter/pyproject.toml
python/src/plugins/nansen/pyproject.toml
python/src/plugins/opensea/pyproject.toml
python/src/plugins/rugcheck/pyproject.toml
python/src/plugins/spl_token/pyproject.toml
python/src/plugins/superfluid/pyproject.toml
python/src/plugins/uniswap/pyproject.toml
python/src/wallets/crossmint/pyproject.toml
python/src/wallets/evm/pyproject.toml
python/src/wallets/solana/pyproject.toml
python/src/wallets/web3/pyproject.toml

- Versioning script (couldn't find a suitable CHANGESET equivalent)
- Autopublish on version bumps
- Dependency conflict check

Python CI/CD

---

typescript/examples/by-wallet/lit/README.md

Fix Lit protocol link

---

typescript/docs/2-set-up-the-project-locally.md

Adds a video guide to "How to setup project locally" guide section
My changes require a change to the project documentation.

Add Video Guide to setup GOAT (Typescript)

---

README.md

This PR adds the MultiversX chain and wallet to the readme of goat-sdk
[PR 398](https://github.com/goat-sdk/goat/pull/398)
This PR updates the readme of goat-sdk to reflect the addition of the MultiversX chain. See PR 398 for the merge triggering this documentation update - https://github.com/goat-sdk/goat/pull/398

Update README.md - Add MultiversX chain and wallet

---

typescript/.changeset/mean-baboons-notice.md
typescript/packages/plugins/hedgey/src/hedgey.service.ts
typescript/packages/plugins/hedgey/src/helpers/error.helper.ts
typescript/packages/plugins/hedgey/src/parameters.ts
typescript/packages/plugins/hedgey/src/types/types.ts

- **Improved output:** The response now includes the token name (`tokenName`) and the chain (`chain`) on which the transaction is executed.
- **Error handling:** The error formatting logic has been extracted into a utility function `getErrorMessage` located in `src/utils/error.helper.ts`, which centralizes error message extraction.
- **Complex type refactor:** Complex types (such as `CampaignInfo`, `ActiveCampaign`, `ProofResult`, `ClaimableCampaign`, and `HedgeyClaimsResponse`) have been extracted and organized into separate files under `src/types/` to improve readability and maintainability.
- **Additional adjustments:** The variable previously named `activeCampaignIds` has been renamed to `activeCampaigns` to better reflect its content, and the redundant function …

refactor(claim): improved output and apply best practices

---

python/src/wallets/solana/goat_wallets/solana/wallet.py

Invoking send_transaction with the wrong parameters.

FIX: send_transaction had wrong parameters

---

README.md

Update README.md to show Irys plugin
[PR 430](https://github.com/goat-sdk/goat/pull/430)
This PR updates the readme of goat-sdk to reflect the addition of the new Irys plugin. See PR 430 for the merge triggering this documentation update - https://github.com/goat-sdk/goat/pull/430

Update README.md - Add Irys plugin

---

README.md

This pr updates the readme.md tool list section by adding the dpsn plugin details .
I have updated the readme.md of the project by adding the dpsn plugin details in the tool list .
If you require releasing a new version of the package:

chore/Update README.md with dpsn plugin details

---

.gitignore

All environment variables are ignored in git

ignore all environment variables
